// Static seed datasets for Orders and Results dashboards.
// Used as fallback when the live API returns no data or fails.
import type { RawResult } from "@/lib/resultsApi";

export const STATIC_ORDERS: any[] = [
  {
    id: "ord-001",
    company: "Hindustan Aeronautics",
    ticker: "HAL",
    order_value: "26000 cr",
    client: "Indian Air Force (MoD)",
    type: "Govt",
    segment: "Defense",
    timeline: "Delivery by FY29",
    explanation:
      "HAL bagged a ₹26,000 Cr contract from the Ministry of Defence for 156 Light Combat Helicopters. The order strengthens HAL's order book visibility through FY29 and reinforces indigenous defence manufacturing under the Atmanirbhar Bharat program.",
    impact: "high",
    confidence: "verified",
    sources: [
      { name: "PIB India", url: "https://pib.gov.in", snippet: "MoD signs contract worth ₹26,000 Cr with HAL for 156 LCH." },
      { name: "Reuters", url: "https://reuters.com", snippet: "India clears HAL chopper deal." },
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    event: "Defence order awarded",
  },
  {
    id: "ord-002",
    company: "Larsen & Toubro",
    ticker: "LT",
    order_value: "15500 cr",
    client: "NHPC / Saudi Aramco",
    type: "International",
    segment: "Infra",
    timeline: "30 months",
    explanation:
      "L&T's hydrocarbon vertical secured a mega offshore EPC order from Saudi Aramco worth ₹15,500 Cr. Execution spans 30 months and adds materially to international order inflows, lifting H2 revenue visibility for the hydrocarbon segment.",
    impact: "high",
    confidence: "verified",
    sources: [
      { name: "BSE Filing", url: "https://bseindia.com", snippet: "L&T informs exchanges of mega international order." },
      { name: "Mint", url: "https://livemint.com", snippet: "Aramco awards EPC contract to L&T." },
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    event: "Contract won",
  },
  {
    id: "ord-003",
    company: "Bharat Electronics",
    ticker: "BEL",
    order_value: "2400 cr",
    client: "Indian Navy",
    type: "Repeat",
    segment: "Defense",
    timeline: "FY26-FY27",
    explanation:
      "BEL received a repeat order worth ₹2,400 Cr for advanced electronic warfare suites for the Indian Navy. The repeat nature underscores stickiness of defence electronics business and pads BEL's already strong order pipeline of over ₹76,000 Cr.",
    impact: "high",
    confidence: "verified",
    sources: [
      { name: "Economic Times", url: "https://economictimes.com", snippet: "BEL wins ₹2,400 Cr Navy order." },
      { name: "BEL filing", url: "https://bel-india.in" },
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    event: "Repeat order received",
  },
  {
    id: "ord-004",
    company: "Tata Power",
    ticker: "TATAPOWER",
    order_value: "1850 cr",
    client: "SJVN Limited",
    type: "New Order",
    segment: "Renewables",
    timeline: "24 months",
    explanation:
      "Tata Power Renewable Energy bagged a 460 MW solar project worth ₹1,850 Cr from SJVN. The win strengthens Tata Power's pivot into utility-scale renewables and adds ~3% to the group's installed solar capacity once commissioned.",
    impact: "high",
    confidence: "single",
    sources: [{ name: "Business Standard", url: "https://business-standard.com", snippet: "Tata Power Renewable wins SJVN solar tender." }],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    event: "Solar order awarded",
  },
  {
    id: "ord-005",
    company: "TCS",
    ticker: "TCS",
    order_value: "9200 cr",
    client: "BSNL",
    type: "Govt",
    segment: "IT",
    timeline: "9 years",
    explanation:
      "TCS won a ₹9,200 Cr advance purchase order from BSNL for Phase-II of the Pan-India 4G/5G rollout. The multi-year deal cements TCS's leadership in indigenous telecom stack deployment and provides annuity revenue through FY33.",
    impact: "high",
    confidence: "verified",
    sources: [
      { name: "Hindu BusinessLine", url: "https://thehindubusinessline.com" },
      { name: "Moneycontrol", url: "https://moneycontrol.com" },
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    event: "Telecom order won",
  },
  {
    id: "ord-006",
    company: "KEC International",
    ticker: "KEC",
    order_value: "1424 cr",
    client: "PowerGrid / Overseas",
    type: "International",
    segment: "Power",
    timeline: "18 months",
    explanation:
      "KEC International secured new T&D and civil orders aggregating ₹1,424 Cr across India and the Americas. The wins lift YTD inflows above ₹15,000 Cr and improve geographic mix toward higher-margin overseas T&D work.",
    impact: "medium",
    confidence: "verified",
    sources: [{ name: "BSE", url: "https://bseindia.com", snippet: "KEC bags new orders worth ₹1,424 Cr." }],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    event: "Multiple orders received",
  },
  {
    id: "ord-007",
    company: "RVNL",
    ticker: "RVNL",
    order_value: "554 cr",
    client: "Central Railway",
    type: "Govt",
    segment: "Infra",
    timeline: "24 months",
    explanation:
      "Rail Vikas Nigam emerged L1 bidder for a ₹554 Cr Central Railway electrification and signaling package. The order supports the Kavach safety rollout and adds incremental visibility to RVNL's FY26 execution pipeline.",
    impact: "medium",
    confidence: "single",
    sources: [{ name: "ET Infra", url: "https://infra.economictimes.com" }],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    event: "L1 bidder declared",
  },
  {
    id: "ord-008",
    company: "Cochin Shipyard",
    ticker: "COCHINSHIP",
    order_value: "488 cr",
    client: "European Client (undisclosed)",
    type: "International",
    segment: "Defense",
    timeline: "20 months",
    explanation:
      "Cochin Shipyard secured an export order worth ₹488 Cr for the construction of two specialised vessels for a European client. The order diversifies revenue away from domestic defence and validates CSL's commercial shipbuilding credentials.",
    impact: "medium",
    confidence: "verified",
    sources: [
      { name: "Mint", url: "https://livemint.com" },
      { name: "CSL filing", url: "https://cochinshipyard.in" },
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    event: "Export order received",
  },
  {
    id: "ord-009",
    company: "Mazagon Dock",
    ticker: "MAZDOCK",
    order_value: "1600 cr",
    client: "Indian Navy",
    type: "Govt",
    segment: "Defense",
    timeline: "36 months",
    explanation:
      "Mazagon Dock received a ₹1,600 Cr refit order for two Kalvari-class submarines from the Indian Navy. The contract is margin-accretive and adds to MDL's already record order book of ~₹38,000 Cr, supporting strong execution into FY28.",
    impact: "high",
    confidence: "verified",
    sources: [{ name: "PIB", url: "https://pib.gov.in" }],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    event: "Navy refit order",
  },
  {
    id: "ord-010",
    company: "Siemens India",
    ticker: "SIEMENS",
    order_value: "750 cr",
    client: "Indian Railways",
    type: "Repeat",
    segment: "Infra",
    timeline: "30 months",
    explanation:
      "Siemens India bagged a repeat ₹750 Cr order for nine-car electric trainsets from Indian Railways. The follow-on order continues the largest locomotive contract globally and is expected to ramp up mobility segment margins.",
    impact: "medium",
    confidence: "verified",
    sources: [{ name: "Reuters", url: "https://reuters.com" }],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    event: "Repeat rail order",
  },
  {
    id: "ord-011",
    company: "Sun Pharma",
    ticker: "SUNPHARMA",
    order_value: "320 cr",
    client: "US Generic Tender",
    type: "International",
    segment: "Pharma",
    timeline: "12 months",
    explanation:
      "Sun Pharma's US subsidiary secured a ₹320 Cr generics supply contract with a major US healthcare procurement consortium. The win improves Taro's specialty mix and offers near-term tailwind to US base business margins.",
    impact: "medium",
    confidence: "single",
    sources: [{ name: "Pharmabiz", url: "https://pharmabiz.com" }],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    event: "Generic supply contract",
  },
  {
    id: "ord-012",
    company: "Ashok Leyland",
    ticker: "ASHOKLEY",
    order_value: "180 cr",
    client: "TN State Transport",
    type: "Repeat",
    segment: "Auto",
    timeline: "6 months",
    explanation:
      "Ashok Leyland received a repeat order for 1,200 BS-VI buses worth ₹180 Cr from Tamil Nadu State Transport. The order strengthens MHCV bus volumes in a seasonally weak quarter and supports market share defense vs Tata Motors.",
    impact: "low",
    confidence: "verified",
    sources: [{ name: "Autocar Pro", url: "https://autocarpro.in" }],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 44).toISOString(),
    event: "STU bus order",
  },
];

export const STATIC_RESULTS: RawResult[] = [
  {
    id: "res-1", ticker: "RELIANCE", company: "Reliance Industries", sector: "Energy", quarter: "Q3 FY26",
    sentiment: "strong", revenue_yoy: 11.4, pat_yoy: 18.2, eps_yoy: 17.6,
    highlight: "Jio ARPU climbs to ₹202; Retail margins expand 60bps QoQ on premiumisation.",
    cmp: 2945, market_cap: 1990000, pe: 26.1,
    sales: { current: 248160, previous: 235481, year_ago: 222820, yoy: 11.4, qoq: 5.4 },
    operating_profit: { current: 43620, previous: 41200, year_ago: 38900, yoy: 12.1, qoq: 5.9 },
    opm: { current: 17.6, previous: 17.5, year_ago: 17.5, yoy: 0.1, qoq: 0.1 },
    pat: { current: 19641, previous: 17394, year_ago: 16613, yoy: 18.2, qoq: 12.9 },
    eps: { current: 29.0, previous: 25.7, year_ago: 24.7, yoy: 17.6, qoq: 12.8 },
    insights: [
      "Jio subscriber adds back to >5M / quarter post tariff hike.",
      "Retail footprint expansion slows but SSSG accelerates to 17%.",
      "O2C margin guidance raised on improving GRMs.",
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
  },
  {
    id: "res-2", ticker: "TCS", company: "Tata Consultancy Services", sector: "IT", quarter: "Q3 FY26",
    sentiment: "strong", revenue_yoy: 9.8, pat_yoy: 13.1, eps_yoy: 13.4,
    highlight: "BSNL ramp + BFSI rebound drive constant-currency growth above peers.",
    cmp: 4180, market_cap: 1512000, pe: 31.2,
    insights: ["Margins expand to 25.6%, beat consensus by 80bps.", "Deal TCV at $11.4Bn — second-best ever."],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: "res-3", ticker: "HDFCBANK", company: "HDFC Bank", sector: "Banking", quarter: "Q3 FY26",
    sentiment: "neutral", revenue_yoy: 7.2, pat_yoy: 4.6, eps_yoy: 4.1,
    highlight: "NIM stable at 3.4%; deposit accretion improves but credit costs tick up.",
    cmp: 1685, market_cap: 1280000, pe: 19.4,
    insights: ["LDR improves 120bps QoQ.", "Slippages elevated in personal loans book."],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "res-4", ticker: "INFY", company: "Infosys", sector: "IT", quarter: "Q3 FY26",
    sentiment: "strong", revenue_yoy: 8.6, pat_yoy: 11.8, eps_yoy: 12.0,
    highlight: "FY26 revenue guidance raised to 4.5–5.5% CC; large deals at $4.7Bn.",
    cmp: 1820, market_cap: 758000, pe: 27.0,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: "res-5", ticker: "TATAMOTORS", company: "Tata Motors", sector: "Auto", quarter: "Q3 FY26",
    sentiment: "strong", revenue_yoy: 14.3, pat_yoy: 41.2, eps_yoy: 39.8,
    highlight: "JLR EBIT margin expands to 9.1%; India PV business swings to profit.",
    cmp: 985, market_cap: 367000, pe: 9.8,
    insights: ["Net auto debt down ₹6,200 Cr QoQ.", "EV portfolio breakeven targeted by H2 FY27."],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
  {
    id: "res-6", ticker: "MARUTI", company: "Maruti Suzuki", sector: "Auto", quarter: "Q3 FY26",
    sentiment: "neutral", revenue_yoy: 6.1, pat_yoy: 3.8, eps_yoy: 3.6,
    highlight: "SUV mix at 62% offsets weak entry-segment volumes; margins flat YoY.",
    cmp: 11240, market_cap: 353000, pe: 28.4,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "res-7", ticker: "SUNPHARMA", company: "Sun Pharmaceutical", sector: "Pharma", quarter: "Q3 FY26",
    sentiment: "strong", revenue_yoy: 12.4, pat_yoy: 21.6, eps_yoy: 21.0,
    highlight: "Specialty business crosses $1Bn run-rate; Ilumya growth above 30%.",
    cmp: 1612, market_cap: 387000, pe: 36.5,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
  },
  {
    id: "res-8", ticker: "ITC", company: "ITC Limited", sector: "FMCG", quarter: "Q3 FY26",
    sentiment: "neutral", revenue_yoy: 5.4, pat_yoy: 2.1, eps_yoy: 2.0,
    highlight: "Cigarette volumes +3%, FMCG margins improve 70bps; agri remains weak.",
    cmp: 462, market_cap: 577000, pe: 25.1,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
  },
  {
    id: "res-9", ticker: "BAJFINANCE", company: "Bajaj Finance", sector: "Finance", quarter: "Q3 FY26",
    sentiment: "weak", revenue_yoy: 18.2, pat_yoy: -3.4, eps_yoy: -3.6,
    highlight: "Credit costs spike on unsecured book stress; AUM growth still 28% YoY.",
    cmp: 6520, market_cap: 405000, pe: 28.2,
    insights: ["Stage-3 assets up 20bps QoQ.", "Management guides for elevated credit costs through H1 FY27."],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
  {
    id: "res-10", ticker: "LT", company: "Larsen & Toubro", sector: "Infra", quarter: "Q3 FY26",
    sentiment: "strong", revenue_yoy: 15.6, pat_yoy: 16.4, eps_yoy: 16.1,
    highlight: "Order inflows at ₹89,000 Cr; international share rises to 51%.",
    cmp: 3680, market_cap: 506000, pe: 36.8,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
  {
    id: "res-11", ticker: "ASIANPAINT", company: "Asian Paints", sector: "Consumer", quarter: "Q3 FY26",
    sentiment: "weak", revenue_yoy: -2.1, pat_yoy: -8.4, eps_yoy: -8.6,
    highlight: "Demand weakness + competitive intensity from Birla Opus weighs on volumes.",
    cmp: 2820, market_cap: 270000, pe: 49.2,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
  },
  {
    id: "res-12", ticker: "HAL", company: "Hindustan Aeronautics", sector: "Defense", quarter: "Q3 FY26",
    sentiment: "strong", revenue_yoy: 19.8, pat_yoy: 24.5, eps_yoy: 24.1,
    highlight: "Order book at ₹1.34 lakh Cr provides 4x revenue visibility.",
    cmp: 4925, market_cap: 329000, pe: 34.6,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "res-13", ticker: "DMART", company: "Avenue Supermarts", sector: "Retail", quarter: "Q3 FY26",
    sentiment: "neutral", revenue_yoy: 17.5, pat_yoy: 6.8, eps_yoy: 6.5,
    highlight: "Revenue growth steady but gross margins compress on general merchandise mix.",
    cmp: 4140, market_cap: 269000, pe: 89.1,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
  },
  {
    id: "res-14", ticker: "JSWSTEEL", company: "JSW Steel", sector: "Metals", quarter: "Q3 FY26",
    sentiment: "weak", revenue_yoy: -4.2, pat_yoy: -22.1, eps_yoy: -22.4,
    highlight: "China dumping + weak realisations drag EBITDA/tonne to ₹8,900.",
    cmp: 905, market_cap: 220000, pe: 21.5,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(),
  },
  {
    id: "res-15", ticker: "ADANIPORTS", company: "Adani Ports & SEZ", sector: "Infra", quarter: "Q3 FY26",
    sentiment: "strong", revenue_yoy: 21.4, pat_yoy: 28.7, eps_yoy: 28.4,
    highlight: "Cargo volumes +24% YoY; Vizhinjam ramp-up adds 6% to throughput.",
    cmp: 1395, market_cap: 301000, pe: 32.9,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
];
